name: darwin

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "macos-11"

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
      - name: "Install Rust (ARM)"
        shell: bash
        run: "rustup target add aarch64-apple-darwin"
      - name: "Build (Intel)"
        shell: bash
        run: |
          examples=("long_running" "nested_shell" "nested_shell_async" "simple_ls" "simple_ls_chan" "simple_ls_rw" "smux")

          for example in "${examples[@]}"; do
              cargo build --target x86_64-apple-darwin --example "$example"
          done

      - name: "Build (ARM)"
        shell: bash
        run: |
          examples=("long_running" "nested_shell" "nested_shell_async" "simple_ls" "simple_ls_chan" "simple_ls_rw" "smux")

          for example in "${examples[@]}"; do
              cargo build --target aarch64-apple-darwin --example "$example"
          done
